"""Add logistics routes

Revision ID: 8c5818b1399c
Revises: 4f84de5734c7
Create Date: 2026-06-29 10:49:57.537305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '8c5818b1399c'
down_revision: Union[str, None] = '4f84de5734c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistics_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('route_manifest', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_routes_id'), 'logistics_routes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistics_routes_id'), table_name='logistics_routes')
    op.drop_table('logistics_routes')
    # ### end Alembic commands ###
